import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Index.module.css";
import HeaderComponent from "../src/components/common/HeaderComponent";
import FooterComponent from "../src/components/common/FooterComponent";
import HomePage from "../src/components/homepage/HomePage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Forside | Stridsbergs & Kvarnstrands</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body>
        <div className={styles.container}>
          <div className={styles.headerContainer}>
            <HeaderComponent />
          </div>
          <div className={styles.imgContainer}></div>
          <div className={styles.content}>
            <HomePage
              header="Kvarnstrands & Stridsbergs AS"
              text="Kvarnstrands & Stridsbergs AS er en av Norges ledende leverandører av
        skjærende verktøy til sagbrukindustrien. Kundene befinner seg fra lengst
        i sør til lengst nord i landet vårt."
              text2=" Hovedmålgruppen er sagbruk og høvlerier, men også papir, cellulose,
        møbelindustrien, metallindustrien, snekkerverksteder og enkeltkunder er
        representert."
              img="https://lh3.googleusercontent.com/pw/ACtC-3dBTWTVWNqG28swA9XWc6SVUKOnIkHx8_bG8ZkrT9up7bgA6_hDytetSXht0EyQax7QIuXAmUAM2_uJ16TA6Fq2hbi44UAR3-l9_h738ymOSwVzT8hwRH9t8vQfCe2HW0uPZhq0kn17-Gvj3gVEHgkE=w1415-h807-no?authuser=0"
            />
          </div>
          <div className={styles.footerContainer}>
            <FooterComponent />
          </div>
        </div>
      </body>
    </div>
  );
}
